dorado_add_library(dorado_basecall
    NAME
        dorado_basecall
    PUBLIC_DIR
        basecall
    SOURCES_PUBLIC
        crf_utils.h
        CudaCaller.h
        CudaModelRunner.h
        DecodedChunk.h
        DecodedChunk.h
        MetalCaller.h
        MetalModelRunner.h
        ModelRunner.h
        ModelRunnerBase.h
    SOURCES_PRIVATE
        ChunkBenchmarks.cpp
        ChunkBenchmarks.h
        crf_utils.cpp
        decode/beam_search.cpp
        decode/beam_search.h
        decode/CPUDecoder.cpp
        decode/CPUDecoder.h
        decode/Decoder.cpp
        decode/Decoder.h
        model/CRFModel.cpp
        model/CRFModel.h
        model/TxModel.cpp
        model/TxModel.h
        ModelRunner.cpp
        ModelRunnerBase.cpp
    DEPENDS_PUBLIC
        dorado_config
        dorado_nn
        dorado_torch_utils
        dorado_utils
        torch_lib
    DEPENDS_PRIVATE
        spdlog::spdlog
)

if(APPLE)
    target_sources(dorado_basecall
        PRIVATE
            caller/MetalCaller.cpp
            caller/MetalLSTMCaller.cpp
            caller/MetalLSTMCaller.h
            caller/MPSCaller.cpp
            caller/MPSCaller.h
            MetalModelRunner.cpp
            model/MetalCRFModel.cpp
            model/MetalCRFModel.h
    )
else()
    target_sources(dorado_basecall
        PRIVATE
            CudaCaller.cpp
            CudaModelRunner.cpp
            decode/CUDADecoder.cpp
            decode/CUDADecoder.h
    )
endif()

if (TARGET koi)
    target_link_libraries(dorado_basecall PRIVATE koi)
endif()
